### ISSUE TITLE
Revisao

### ISSUE THREAD

**Issue by eckowz** [eckowz/soNaSexta#10]

**Comment by eckowz** [comment]
-a ajustar documentos, foco no anunciante.
-mais de um anuncio ao mesmo tempo? exclusivo?
-faixas de exibição? alto fluxo, baixo, etc. Qual é o metodo que o fluxo é dividido.
-modo de compra

**Comment by KatsutoshiRF** [comment]
A propaganda não interrompe o vídeo. Anuncio na lateral ou acima do vídeo.
Anuncio exclusivo : exibição por pagina;
Anuncio não exclusivo : exibição por tempo(30 s);

**Comment by KatsutoshiRF** [comment]
Valores divididos por número de acessos levando em conta a exclusivdade.
Se exclusivo: número X de visualizações por acessos únicos a página.
Se não for exclusivo: números X de visualizações.

**Comment by KatsutoshiRF** [comment]
Anunciante divide com as visualizações do TA002, qual dia da semana, qual horário, faixa e se for exclusivo.
Valores são exibidos em tela.
